sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
script:
- "./package.sh"
before_deploy:
- export RELEASE_FILE=bin.tar.gz
- ls
- echo "Deploying $RELEASE_FILE to GitHub"
deploy:
  provider: releases
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: Malfoy/BTRIM
    overwrite: true
  api-key:
    secure: scDvcodj0f7uZNGk7xrWluWODKByHXgCTYremC6Lpz6xylMer36gDkCL8ywS82J1Ceo28fkTPbLRsUy45Vn/rdd0LN1uIZWylVsrU/LgLY1eMAR2mlo4J7moXj6rLUeu8eQP3ti8j7+wNFe9zUN6JrgFsEc7unnYiUhNLIs24Ab5bymTKoU47hek7dWLOKp4zj/P9HMbCFce55YQ4bNk/kkrUDbFxWpdQumMtCHt2g9qfiF+UKb4JInfyM5pL34xCB7+KCZCT/1C/tsnItZPraCgwG5XyUezhcUd4yxRP+lwc9qh3hE4QQiV7uEygoT/arJQ8eZRcPPmi2VB/8h/T53/0wxtjtrZHX7hwNO4L1bkGTSGnbRfAxbex4OIWj5JFupeR7mzeA2uRx0bC8ZMc2zCK30aJ/Ynwnmrka895QJMwqxVfFrleeeHhOkDNCtk4THVmMmnxcWAvji6OyvxdUpla51POpG5xArwtbydbstSAeFRLJjlX/N1yMr++YWEq5fpZ1Pn9voETrdV6yd/PVnpvBC2Ldr1w76F6jP6uGkrU3cIkCFYr49z2lbe/p1YDePOvco/ETV38ju2ovOXBPO1L+weFl+zajThgteX7ACiRqkqA63gaZGgh++M2oonR/XM44aK/mpJClBBm1OaVgQiQdb0I0SlrPxbmed66A4=
